# Generated by Django 4.2.1 on 2023-05-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locadora", "0002_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="categoria",
            field=models.ManyToManyField(to="locadora.categoria"),
        ),
    ]
