# Generated by Django 4.2.1 on 2023-05-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locadora", "0003_filme_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Locacao",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("data", models.DateField(auto_now=True)),
            ],
        ),
    ]
