# Generated by Django 4.2.1 on 2023-05-28 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locadora", "0004_cliente_locacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="locacao",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locadora.cliente",
            ),
        ),
    ]
